### PR TITLE
Bugfix: Change Label width

### LINKED ISSUE #111: Bug: Full filename is not shown in List view even if there is space
### Description
In the desktop view of the list view long filenames are not fully shown even if there is a lot of space for them 

### Steps to Reproduce

1. Change the name of a file to Example asset 1 final_final_v20_final
2. Switch to the list view 

#### Expected behavior
Since there is a lot of space in the table, I would expect the whole filename to be shown. This is especially visible with big browser windows. 

#### Actual behavior
The filename is cut off. 

Bildschirmfoto 2022-01-04 um 11 51 35

### Affected Versions

Media Module: 0.6.2

### PR DESCRIPTION
**Pull request by pKallert**
closes #111 

**What I did**
Currently with very long file names, the filename is not fully shown in Listview. This happens even if there is space to show the whole filename. I changed that to show the full filename. 

**How I did it**
I changed the fixed width of the label to a minwidth. 
This shows more of the label but with very long labels this creates a horizontal scrollbar. Perhaps changing up the whole table with fixed widths could solve this. 

**How to verify it**
Long filenames in listview are now fully shown if the window is big enough. 

Old behavior: 

Bildschirmfoto 2022-01-04 um 11 51 35

New Behavior: 

Bildschirmfoto 2022-01-04 um 14 03 59

### CODE REVIEW

**Comment by Sebobo** [comment]
Hi @pKallert,

thx for the change. I intentionally wanted to prevent the scrollbar, as it can be really confusing if suddenly the controls get lost due to the horizontal scroll. Therefore I decided to use a width that would work well in the lowest supported screen width. I already spent some timing trying to get the ellipsis working inside the column, but without success.
That would be the perfect solution and should also somehow be possible, I just didn't want to spend more time on this for now.

Do you want to take another shot at trying to make the ellipsis work with a variable width?

**Review by Sebobo — CHANGES_REQUESTED** [review]
See my other comment

**Comment by pKallert** [comment]
@Sebobo  
Sure, I will have a look. This must work somehow, even with tables 👍

**Comment by pKallert** [comment]
@Sebobo 
could you have another look at the changes? 

All columns are now at their minimum width, while the label-columns fits the remaining content. It is a little bit hacky, but with tables there is no better solution I could find 🤷 

Bildschirmfoto 2022-01-21 um 09 07 24


Also, I made the table header sticky. If you prefer it the old way, I can remove it 👍

**Comment by Sebobo** [comment]
@pKallert awesome thx, will check it out 🙂

**Review by Sebobo — APPROVED** [review]
Awesome :)

**Pull request merged**
